name: tests
on:
  push:
    branches:
      - '**'

env:
  GOPATH: /go_path
  GOCACHE: /go_cache

jobs:
  lint:
    name: Release
    runs-on: ubuntu-20.04
    steps:

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1
      with:
        go-version: '>=1.20.1'
